//! Emits allocation-free typed wire codecs from the protocol IR.

const std = @import("std");
const protocol_ir = @import("protocol.zig");

pub const Error = std.mem.Allocator.Error || error{
    InvalidEnumType,
    InvalidEnumValue,
};

pub fn generate(
    allocator: std.mem.Allocator,
    protocol: protocol_ir.Protocol,
) Error![]u8 {
    var output: std.ArrayList(u8) = .empty;
    errdefer output.deinit(allocator);
    try add(&output, allocator,
        \\// Generated by wayring-scanner. Do not edit.
        \\const std = @import("std");
        \\const wayring = @import("wayring");
        \\const wire = wayring.wire;
        \\const ancillary = wayring.ancillary;
        \\const tx = wayring.tx;
        \\const metadata = wayring.metadata;
        \\const native_endian = @import("builtin").cpu.arch.endian();
        \\
        \\pub const DynamicNewId = struct {
        \\    interface: []const u8,
        \\    version: u32,
        \\    id: u32,
        \\};
        \\
        \\fn variableSize(len: usize, terminator: usize) error{LengthOverflow}!usize {
        \\    const wire_len = std.math.add(usize, len, terminator) catch return error.LengthOverflow;
        \\    if (wire_len > std.math.maxInt(u32)) return error.LengthOverflow;
        \\    const padded = std.math.add(usize, wire_len, 3) catch return error.LengthOverflow;
        \\    return std.math.add(usize, 4, padded & ~@as(usize, 3)) catch return error.LengthOverflow;
        \\}
        \\
        \\fn writeU32(reservation: *tx.Reservation, value: u32) tx.Error!void {
        \\    var bytes: [4]u8 = undefined;
        \\    std.mem.writeInt(u32, &bytes, value, native_endian);
        \\    try reservation.write(&bytes);
        \\}
        \\
        \\fn writeString(reservation: *tx.Reservation, value: ?[]const u8) tx.Error!void {
        \\    const bytes = value orelse {
        \\        try writeU32(reservation, 0);
        \\        return;
        \\    };
        \\    const wire_len = bytes.len + 1;
        \\    try writeU32(reservation, @intCast(wire_len));
        \\    try reservation.write(bytes);
        \\    const zeros = [_]u8{0} ** 4;
        \\    try reservation.write(zeros[0 .. 1 + ((4 - wire_len % 4) % 4)]);
        \\}
        \\
        \\fn writeArray(reservation: *tx.Reservation, value: ?[]const u8) tx.Error!void {
        \\    const bytes = value orelse &.{};
        \\    try writeU32(reservation, @intCast(bytes.len));
        \\    try reservation.write(bytes);
        \\    const zeros = [_]u8{0} ** 3;
        \\    try reservation.write(zeros[0..((4 - bytes.len % 4) % 4)]);
        \\}
        \\
    );
    for (protocol.interfaces) |interface| {
        try emitInterface(&output, allocator, protocol, interface);
    }
    return output.toOwnedSlice(allocator);
}

fn emitInterface(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    protocol: protocol_ir.Protocol,
    interface: protocol_ir.Interface,
) Error!void {
    try add(output, allocator, "pub const ");
    try identifier(output, allocator, interface.name);
    try add(output, allocator, " = struct {\n    pub const version: u32 = ");
    try unsigned(output, allocator, interface.version);
    try add(output, allocator, ";\n    pub const info: metadata.Interface = .{\n        .name = \"");
    try add(output, allocator, interface.name);
    try add(output, allocator, "\",\n        .version = version,\n        .requests = &.{\n");
    for (interface.requests) |message| try emitMetadata(output, allocator, message);
    try add(output, allocator, "        },\n        .events = &.{\n");
    for (interface.events) |message| try emitMetadata(output, allocator, message);
    try add(output, allocator, "        },\n    }");
    try add(output, allocator,
        \\;
        \\    pub const DecodeError = wire.DecodeError || ancillary.Error || error{
        \\        UnknownOpcode,
        \\        UnexpectedNull,
        \\        NullObject,
        \\    };
        \\    pub const EncodeError = wire.EncodeError || tx.Error || error{
        \\        LengthOverflow,
        \\        MessageTooLarge,
        \\        InvalidString,
        \\        NullObject,
        \\        NoMessages,
        \\    };
        \\
    );
    try emitEnums(output, allocator, protocol, interface);
    try emitDirection(output, allocator, "Request", interface.requests);
    try emitClientConstructors(output, allocator, protocol, interface);
    try emitServerAdmissions(output, allocator, protocol, interface);
    try emitDirection(output, allocator, "Event", interface.events);
    try add(output, allocator, "};\n\n");
}

fn emitClientConstructors(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    protocol: protocol_ir.Protocol,
    interface: protocol_ir.Interface,
) Error!void {
    for (interface.requests) |message| {
        var new_id_count: usize = 0;
        for (message.arguments) |argument| if (argument.type == .new_id) {
            new_id_count += 1;
        };
        if (new_id_count == 0) continue;

        try add(output, allocator, "    pub const Constructor_");
        try add(output, allocator, message.name);
        try add(output, allocator, " = struct {\n");
        for (message.arguments) |argument| {
            try add(output, allocator, "        ");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, ": ");
            if (argument.type != .new_id) {
                try emitType(output, allocator, argument);
            } else if (argument.interface == null) {
                if (argument.allow_null) try add(output, allocator, "?");
                try add(output, allocator, "wayring.client.NewObject");
            } else {
                if (argument.allow_null) try add(output, allocator, "?");
                const local_child = hasInterface(protocol, argument.interface.?);
                try add(
                    output,
                    allocator,
                    if (local_child)
                        "wayring.client.NewObjectContext"
                    else
                        "wayring.client.TypedNewObject",
                );
                if (local_child and !argument.allow_null) try add(output, allocator, " = .{}");
            }
            try add(output, allocator, ",\n");
        }
        try add(output, allocator, "    };\n\n    pub const Constructed_");
        try add(output, allocator, message.name);
        try add(output, allocator, " = struct {\n");
        for (message.arguments) |argument| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "        ");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, if (argument.allow_null)
                ": ?wayring.objects.Handle,\n"
            else
                ": wayring.objects.Handle,\n");
        }
        try add(output, allocator, "    };\n\n    pub fn construct_");
        try add(output, allocator, message.name);
        try add(output, allocator,
            \\(client_objects: *wayring.objects.ClientObjects, queue: *tx.Queue, parent: wayring.objects.Handle, payload: Constructor_
        );
        try add(output, allocator, message.name);
        try add(output, allocator, ") !Constructed_");
        try add(output, allocator, message.name);
        try add(output, allocator,
            \\ {
            \\        const parent_object = client_objects.namespace.resolve(parent) orelse return error.StaleHandle;
            \\        if (parent_object.interface != &info) return error.WrongInterface;
        );
        for (message.arguments) |argument| {
            if (argument.type != .new_id or argument.interface == null or
                hasInterface(protocol, argument.interface.?)) continue;
            if (argument.allow_null) {
                try add(output, allocator, "        if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ") |specification| if (!std.mem.eql(u8, specification.interface.name, \"");
            } else {
                try add(output, allocator, "        if (!std.mem.eql(u8, payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface.name, \"");
            }
            try add(output, allocator, argument.interface.?);
            try add(output, allocator, "\")) return error.WrongInterface;\n");
        }
        for (message.arguments, 0..) |argument, index| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "        const new_object_");
            try unsigned(output, allocator, index);
            if (argument.allow_null) try add(output, allocator, ": ?wayring.objects.Handle");
            try add(output, allocator, " = ");
            if (argument.allow_null) {
                try add(output, allocator, "if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ") |specification| try client_objects.createLocal(");
            } else {
                try add(output, allocator, "try client_objects.createLocal(");
            }
            if (argument.interface) |child_interface| {
                const local_child = hasInterface(protocol, child_interface);
                if (!local_child) {
                    try add(output, allocator, "payload.");
                    try identifier(output, allocator, argument.name);
                    if (argument.allow_null) try add(output, allocator, ".?");
                    try add(output, allocator, ".interface, @min(parent_object.version, payload.");
                    try identifier(output, allocator, argument.name);
                    if (argument.allow_null) try add(output, allocator, ".?");
                    try add(output, allocator, ".interface.version), ");
                } else {
                    try add(output, allocator, "&");
                    try emitChildInterface(output, allocator, interface.name, child_interface);
                    try add(output, allocator, ".info, @min(parent_object.version, ");
                    try emitChildInterface(output, allocator, interface.name, child_interface);
                    try add(output, allocator, ".info.version), ");
                }
                if (argument.allow_null) {
                    try add(output, allocator, "specification.context");
                } else {
                    try add(output, allocator, "payload.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".context");
                }
            } else {
                const prefix = if (argument.allow_null) "specification" else "payload.";
                try add(output, allocator, prefix);
                if (!argument.allow_null) try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface, ");
                try add(output, allocator, prefix);
                if (!argument.allow_null) try identifier(output, allocator, argument.name);
                try add(output, allocator, ".version, ");
                try add(output, allocator, prefix);
                if (!argument.allow_null) try identifier(output, allocator, argument.name);
                try add(output, allocator, ".context");
            }
            try add(output, allocator, if (argument.allow_null) ") else null;\n" else ");\n");
            if (argument.allow_null) {
                try add(output, allocator, "        errdefer if (new_object_");
                try unsigned(output, allocator, index);
                try add(output, allocator, ") |handle| { _ = client_objects.cancelLocal(handle) catch unreachable; }\n");
            } else {
                try add(output, allocator, "        errdefer _ = client_objects.cancelLocal(new_object_");
                try unsigned(output, allocator, index);
                try add(output, allocator, ") catch unreachable;\n");
            }
        }
        try add(output, allocator, "        try wayring.client.sendRequest(@This(), client_objects, queue, parent, .{ .");
        try identifier(output, allocator, message.name);
        try add(output, allocator, " = .{\n");
        for (message.arguments, 0..) |argument, index| {
            try add(output, allocator, "            .");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, " = ");
            if (argument.type != .new_id) {
                try add(output, allocator, "payload.");
                try identifier(output, allocator, argument.name);
            } else if (argument.interface != null) {
                if (argument.allow_null) try add(output, allocator, "if (new_object_");
                if (argument.allow_null) {
                    try unsigned(output, allocator, index);
                    try add(output, allocator, ") |handle| handle.id else null");
                } else {
                    try add(output, allocator, "new_object_");
                    try unsigned(output, allocator, index);
                    try add(output, allocator, ".id");
                }
            } else {
                if (argument.allow_null) {
                    try add(output, allocator, "if (new_object_");
                    try unsigned(output, allocator, index);
                    try add(output, allocator, ") |handle| .{ .interface = payload.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".?.interface.name, .version = payload.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".?.version, .id = handle.id } else null");
                } else {
                    try add(output, allocator, ".{ .interface = payload.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".interface.name, .version = payload.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".version, .id = new_object_");
                    try unsigned(output, allocator, index);
                    try add(output, allocator, ".id }");
                }
            }
            try add(output, allocator, ",\n");
        }
        try add(output, allocator, "        } });\n        return .{\n");
        for (message.arguments, 0..) |argument, index| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "            .");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, " = new_object_");
            try unsigned(output, allocator, index);
            try add(output, allocator, ",\n");
        }
        try add(output, allocator, "        };\n    }\n\n");
    }
}

fn emitServerAdmissions(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    protocol: protocol_ir.Protocol,
    interface: protocol_ir.Interface,
) Error!void {
    for (interface.requests) |message| {
        var has_new_id = false;
        var has_typed_new_id = false;
        for (message.arguments) |argument| {
            if (argument.type == .new_id) {
                has_new_id = true;
                if (argument.interface != null) has_typed_new_id = true;
            }
        }
        if (!has_new_id) continue;

        try add(output, allocator, "    pub const NewObjects_");
        try add(output, allocator, message.name);
        try add(output, allocator, " = struct {\n");
        for (message.arguments) |argument| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "        ");
            try identifier(output, allocator, argument.name);
            if (argument.interface != null and hasInterface(protocol, argument.interface.?)) {
                try add(output, allocator, ": ?*anyopaque = null,\n");
            } else {
                try add(output, allocator, ": wayring.server.NewObject,\n");
            }
        }
        try add(output, allocator, "    };\n\n    pub const Admitted_");
        try add(output, allocator, message.name);
        try add(output, allocator, " = struct {\n");
        for (message.arguments) |argument| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "        ");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, ": wayring.objects.Handle,\n");
        }
        try add(output, allocator, "    };\n\n    pub fn admit_");
        try add(output, allocator, message.name);
        try add(output, allocator, "(server_objects: anytype, parent: wayring.objects.Handle, payload: Request_");
        try add(output, allocator, message.name);
        try add(output, allocator, ", new_objects: NewObjects_");
        try add(output, allocator, message.name);
        try add(output, allocator, ") !Admitted_");
        try add(output, allocator, message.name);
        try add(output, allocator,
            \\ {
            \\        const parent_object = server_objects.namespace.resolve(parent) orelse return error.StaleHandle;
            \\        if (parent_object.interface != &info) return error.WrongInterface;
        );
        if (has_typed_new_id) {
            try add(output, allocator, "        const parent_version = parent_object.version;\n");
        }
        for (message.arguments) |argument| {
            if (argument.type != .new_id) continue;
            if (argument.interface) |child_interface| {
                if (hasInterface(protocol, child_interface)) continue;
                try add(output, allocator, "        if (!std.mem.eql(u8, new_objects.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface.name, \"");
                try add(output, allocator, child_interface);
                try add(output, allocator, "\")) return error.WrongInterface;\n");
            } else {
                try add(output, allocator, "        if (!std.mem.eql(u8, new_objects.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface.name, payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface)) return error.WrongInterface;\n        try new_objects.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface.validateVersion(payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".version);\n");
            }
        }
        for (message.arguments, 0..) |argument, index| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "        const new_object_");
            try unsigned(output, allocator, index);
            try add(output, allocator, " = try server_objects.insertClient(payload.");
            try identifier(output, allocator, argument.name);
            if (argument.interface == null) try add(output, allocator, ".id");
            try add(output, allocator, ", ");
            if (argument.interface) |child_interface| {
                if (hasInterface(protocol, child_interface)) {
                    try add(output, allocator, "&");
                    try emitChildInterface(output, allocator, interface.name, child_interface);
                    try add(output, allocator, ".info, @min(parent_version, ");
                    try emitChildInterface(output, allocator, interface.name, child_interface);
                    try add(output, allocator, ".info.version), new_objects.");
                    try identifier(output, allocator, argument.name);
                } else {
                    try add(output, allocator, "new_objects.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".interface, @min(parent_version, new_objects.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".interface.version), new_objects.");
                    try identifier(output, allocator, argument.name);
                    try add(output, allocator, ".context");
                }
            } else {
                try add(output, allocator, "new_objects.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".interface, payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".version, new_objects.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".context");
            }
            try add(output, allocator, ");\n        errdefer _ = server_objects.removeClient(new_object_");
            try unsigned(output, allocator, index);
            try add(output, allocator, ") catch unreachable;\n");
        }
        try add(output, allocator, "        return .{\n");
        for (message.arguments, 0..) |argument, index| {
            if (argument.type != .new_id) continue;
            try add(output, allocator, "            .");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, " = new_object_");
            try unsigned(output, allocator, index);
            try add(output, allocator, ",\n");
        }
        try add(output, allocator, "        };\n    }\n\n");
    }
}

fn hasInterface(protocol: protocol_ir.Protocol, name: []const u8) bool {
    for (protocol.interfaces) |interface| {
        if (std.mem.eql(u8, interface.name, name)) return true;
    }
    return false;
}

fn emitChildInterface(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    parent: []const u8,
    child: []const u8,
) Error!void {
    if (std.mem.eql(u8, parent, child))
        try add(output, allocator, "@This()")
    else
        try identifier(output, allocator, child);
}

fn emitEnums(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    protocol: protocol_ir.Protocol,
    interface: protocol_ir.Interface,
) Error!void {
    for (interface.enums) |protocol_enum| {
        const signed = try enumIsSigned(protocol, interface.name, protocol_enum);
        const backing = if (signed) "i32" else "u32";
        try add(output, allocator, "    pub const ");
        try identifier(output, allocator, protocol_enum.name);
        try add(output, allocator, " = extern struct {\n        value: ");
        try add(output, allocator, backing);
        try add(output, allocator, ",\n\n");
        for (protocol_enum.entries) |entry| {
            try add(output, allocator, "        pub const ");
            try identifier(output, allocator, entry.name);
            try add(output, allocator, ": @This() = .{ .value = ");
            if (signed) {
                try unsigned(output, allocator, std.math.cast(i32, entry.value) orelse
                    return error.InvalidEnumValue);
            } else {
                try unsigned(output, allocator, std.math.cast(u32, entry.value) orelse
                    return error.InvalidEnumValue);
            }
            try add(output, allocator, " };\n");
        }
        try add(output, allocator, "\n        pub inline fn fromInt(value: ");
        try add(output, allocator, backing);
        try add(output, allocator, ") @This() {\n            return .{ .value = value };\n        }\n\n        pub inline fn toInt(value: @This()) ");
        try add(output, allocator, backing);
        try add(output, allocator, " {\n            return value.value;\n        }\n");
        if (protocol_enum.bitfield) {
            try add(output, allocator,
                \\
                \\        pub inline fn contains(value: @This(), flag: @This()) bool {
                \\            return value.value & flag.value == flag.value;
                \\        }
                \\
            );
        }
        try add(output, allocator, "    };\n\n");
    }
}

fn enumIsSigned(
    protocol: protocol_ir.Protocol,
    owner_name: []const u8,
    protocol_enum: protocol_ir.Enum,
) Error!bool {
    var signed: ?bool = null;
    for (protocol.interfaces) |interface| {
        for (interface.requests) |message| try inspectEnumArguments(
            interface.name,
            owner_name,
            protocol_enum.name,
            message.arguments,
            &signed,
        );
        for (interface.events) |message| try inspectEnumArguments(
            interface.name,
            owner_name,
            protocol_enum.name,
            message.arguments,
            &signed,
        );
    }
    if (signed) |value| return value;
    for (protocol_enum.entries) |entry| if (entry.value < 0) return true;
    return false;
}

fn inspectEnumArguments(
    consumer_name: []const u8,
    owner_name: []const u8,
    enum_name: []const u8,
    arguments: []const protocol_ir.Argument,
    signed: *?bool,
) Error!void {
    for (arguments) |argument| {
        const reference = argument.enum_name orelse continue;
        if (!enumReferenceMatches(reference, consumer_name, owner_name, enum_name)) continue;
        const current = switch (argument.type) {
            .int => true,
            .uint => false,
            else => return error.InvalidEnumType,
        };
        if (signed.*) |previous| {
            if (previous != current) return error.InvalidEnumType;
        } else signed.* = current;
    }
}

fn enumReferenceMatches(
    reference: []const u8,
    consumer_name: []const u8,
    owner_name: []const u8,
    enum_name: []const u8,
) bool {
    if (std.mem.eql(u8, reference, enum_name))
        return std.mem.eql(u8, consumer_name, owner_name);
    const separator = std.mem.indexOfScalar(u8, reference, '.') orelse return false;
    return std.mem.eql(u8, reference[0..separator], owner_name) and
        std.mem.eql(u8, reference[separator + 1 ..], enum_name);
}

fn emitMetadata(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    message: protocol_ir.Message,
) Error!void {
    try add(output, allocator, "            .{ .since = ");
    try unsigned(output, allocator, message.since);
    if (message.destructor)
        try add(output, allocator, ", .destructor = true")
    else
        try add(output, allocator, "");
    try add(output, allocator, " },\n");
}

fn emitDirection(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime direction: []const u8,
    messages: []const protocol_ir.Message,
) Error!void {
    try add(output, allocator, "    pub const " ++ direction ++ " = union(enum) {\n");
    if (messages.len == 0) {
        try add(output, allocator, "        _none: void,\n");
    } else for (messages) |message| {
        try add(output, allocator, "        ");
        try identifier(output, allocator, message.name);
        try add(output, allocator, ": " ++ direction ++ "_");
        try add(output, allocator, message.name);
        try add(output, allocator, ",\n");
    }
    try add(output, allocator, "    };\n\n");

    for (messages) |message| {
        try add(output, allocator, "    pub const " ++ direction ++ "_");
        try add(output, allocator, message.name);
        try add(output, allocator, " = struct {\n");
        for (message.arguments) |argument| {
            try add(output, allocator, "        ");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, ": ");
            try emitType(output, allocator, argument);
            try add(output, allocator, ",\n");
        }
        try add(output, allocator, "    };\n\n");
    }

    try add(output, allocator, "    pub fn decode" ++ direction ++ "(\n");
    try add(output, allocator,
        \\        message: wire.Message,
        \\        fds: *ancillary.FdQueue,
        \\    ) DecodeError!
    );
    try add(output, allocator, direction);
    try add(output, allocator, " {\n");
    var has_fds = false;
    for (messages) |message| for (message.arguments) |argument| {
        if (argument.type == .fd) has_fds = true;
    };
    if (!has_fds) try add(output, allocator, "        _ = fds;\n");
    try add(output, allocator, "        return switch (message.header.opcode) {\n");
    for (messages) |message| try emitDecoderCase(output, allocator, message);
    try add(output, allocator,
        \\            else => error.UnknownOpcode,
        \\        };
        \\    }
        \\
    );
    try emitEncoder(output, allocator, direction, messages);
}

fn emitEncoder(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime direction: []const u8,
    messages: []const protocol_ir.Message,
) Error!void {
    const function_direction: []const u8 = comptime if (std.mem.eql(u8, direction, "Request"))
        "request"
    else
        "event";
    try add(output, allocator, "    pub fn encode" ++ direction ++ "(queue: *tx.Queue, object_id: u32, value: " ++ direction ++ ") EncodeError!void {\n");
    if (messages.len == 0) {
        try add(output, allocator,
            \\        _ = queue;
            \\        _ = object_id;
            \\        _ = value;
            \\        return error.NoMessages;
            \\    }
            \\
        );
    } else {
        try add(output, allocator, "        return switch (value) {\n");
        for (messages) |message| {
            try add(output, allocator, "            .");
            try identifier(output, allocator, message.name);
            try add(output, allocator, " => |payload| encode" ++ direction ++ "_");
            try add(output, allocator, message.name);
            try add(output, allocator, "(queue, object_id, payload),\n");
        }
        try add(output, allocator, "        };\n    }\n\n");
    }

    try add(output, allocator, "    pub inline fn " ++ function_direction ++ "Size(value: " ++ direction ++ ") EncodeError!usize {\n");
    if (messages.len == 0) {
        try add(output, allocator, "        _ = value;\n        return error.NoMessages;\n    }\n\n");
    } else {
        try add(output, allocator, "        return switch (value) {\n");
        for (messages) |message| {
            try add(output, allocator, "            .");
            try identifier(output, allocator, message.name);
            try add(output, allocator, " => |payload| " ++ function_direction ++ "Size_");
            try add(output, allocator, message.name);
            try add(output, allocator, "(payload),\n");
        }
        try add(output, allocator, "        };\n    }\n\n");
    }

    for (messages) |message| try emitMessageEncoder(
        output,
        allocator,
        direction,
        function_direction,
        message,
    );
}

fn emitMessageEncoder(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime direction: []const u8,
    comptime function_direction: []const u8,
    message: protocol_ir.Message,
) Error!void {
    try add(output, allocator, "    inline fn " ++ function_direction ++ "Size_");
    try add(output, allocator, message.name);
    try add(output, allocator, "(payload: " ++ direction ++ "_");
    try add(output, allocator, message.name);
    try add(output, allocator, ") EncodeError!usize {\n");
    var has_byte_arguments = false;
    var payload_used = false;
    for (message.arguments) |argument| {
        if (argument.type != .fd) has_byte_arguments = true;
        payload_used = payload_used or switch (argument.type) {
            .string, .array => true,
            .object => !argument.allow_null,
            .new_id => argument.interface == null or !argument.allow_null,
            .int, .uint, .fixed, .fd => false,
        };
    }
    if (!payload_used) try add(output, allocator, "        _ = payload;\n");
    try add(
        output,
        allocator,
        if (has_byte_arguments)
            "        var size: usize = wire.header_len;\n"
        else
            "        const size: usize = wire.header_len;\n",
    );
    for (message.arguments) |argument| try emitSizeValidation(output, allocator, argument);
    try add(output, allocator,
        \\        if (size > wire.max_message_len) return error.MessageTooLarge;
        \\        return size;
        \\    }
        \\
    );

    try add(output, allocator, "    fn encode" ++ direction ++ "_");
    try add(output, allocator, message.name);
    try add(output, allocator, "(queue: *tx.Queue, object_id: u32, payload: " ++ direction ++ "_");
    try add(output, allocator, message.name);
    try add(output, allocator, ") EncodeError!void {\n        if (object_id == 0) return error.NullSender;\n");
    if (message.arguments.len == 0) try add(output, allocator, "        _ = payload;\n");
    try add(
        output,
        allocator,
        if (has_byte_arguments)
            "        var size: usize = wire.header_len;\n"
        else
            "        const size: usize = wire.header_len;\n",
    );
    for (message.arguments) |argument| try emitSizeValidation(output, allocator, argument);
    try add(output, allocator,
        \\        if (size > wire.max_message_len) return error.MessageTooLarge;
        \\        var reservation = try queue.reserve(size);
        \\        errdefer reservation.abort();
        \\        var header: [wire.header_len]u8 = undefined;
        \\        try (wire.Header{
        \\            .object_id = object_id,
        \\            .opcode = 
    );
    try unsigned(output, allocator, message.opcode);
    try add(output, allocator,
        \\,
        \\            .size = @intCast(size),
        \\        }).encode(&header);
        \\        try reservation.write(&header);
    );
    for (message.arguments) |argument| try emitEncodeArgument(output, allocator, argument);
    try add(output, allocator, "        try reservation.commit(&.{");
    var first_fd = true;
    for (message.arguments) |argument| {
        if (argument.type != .fd) continue;
        if (!first_fd) try add(output, allocator, ", ");
        first_fd = false;
        try add(output, allocator, "payload.");
        try identifier(output, allocator, argument.name);
    }
    try add(output, allocator, "});\n    }\n\n");
}

fn emitSizeValidation(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    argument: protocol_ir.Argument,
) Error!void {
    switch (argument.type) {
        .int, .uint, .fixed => try add(output, allocator, "        size += 4;\n"),
        .object => {
            if (!argument.allow_null) {
                try add(output, allocator, "        if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, " == 0) return error.NullObject;\n");
            }
            try add(output, allocator, "        size += 4;\n");
        },
        .new_id => if (argument.interface == null) {
            try add(output, allocator, "        if (payload.");
            try identifier(output, allocator, argument.name);
            try add(output, allocator, ".id == 0) return error.NullObject;\n        {\n            const bytes = payload.");
            try identifier(output, allocator, argument.name);
            try add(output, allocator,
                \\.interface;
                \\            if (std.mem.indexOfScalar(u8, bytes, 0) != null) return error.InvalidString;
                \\            size = std.math.add(usize, size, try variableSize(bytes.len, 1)) catch return error.LengthOverflow;
                \\        }
                \\        size += 8;
            );
        } else {
            if (!argument.allow_null) {
                try add(output, allocator, "        if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, " == 0) return error.NullObject;\n");
            }
            try add(output, allocator, "        size += 4;\n");
        },
        .fd => {},
        .string => {
            if (argument.allow_null) {
                try add(output, allocator, "        if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ") |bytes| {\n");
            } else {
                try add(output, allocator, "        {\n            const bytes = payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ";\n");
            }
            try add(output, allocator,
                \\            if (std.mem.indexOfScalar(u8, bytes, 0) != null) return error.InvalidString;
                \\            size = std.math.add(usize, size, try variableSize(bytes.len, 1)) catch return error.LengthOverflow;
                \\        }
            );
            if (argument.allow_null) try add(output, allocator, "        else size += 4;\n");
        },
        .array => {
            if (argument.allow_null) {
                try add(output, allocator, "        if (payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ") |bytes| size = std.math.add(usize, size, try variableSize(bytes.len, 0)) catch return error.LengthOverflow else size += 4;\n");
            } else {
                try add(output, allocator, "        size = std.math.add(usize, size, try variableSize(payload.");
                try identifier(output, allocator, argument.name);
                try add(output, allocator, ".len, 0)) catch return error.LengthOverflow;\n");
            }
        },
    }
}

fn emitEncodeArgument(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    argument: protocol_ir.Argument,
) Error!void {
    if (argument.type == .fd) return;
    if (argument.type == .new_id and argument.interface == null) {
        try add(output, allocator, "        try writeString(&reservation, payload.");
        try identifier(output, allocator, argument.name);
        try add(output, allocator, ".interface);\n        try writeU32(&reservation, payload.");
        try identifier(output, allocator, argument.name);
        try add(output, allocator, ".version);\n        try writeU32(&reservation, payload.");
        try identifier(output, allocator, argument.name);
        try add(output, allocator, ".id);\n");
        return;
    }
    if (argument.enum_name != null) {
        try add(output, allocator, "        try writeU32(&reservation, ");
        if (argument.type == .int) try add(output, allocator, "@bitCast(");
        try add(output, allocator, "payload.");
        try identifier(output, allocator, argument.name);
        try add(output, allocator, ".value");
        if (argument.type == .int) try add(output, allocator, ")");
        try add(output, allocator, ");\n");
        return;
    }
    try add(output, allocator, "        ");
    switch (argument.type) {
        .int, .fixed => try add(output, allocator, "try writeU32(&reservation, @bitCast(payload."),
        .uint => try add(output, allocator, "try writeU32(&reservation, payload."),
        .object, .new_id => if (argument.allow_null)
            try add(output, allocator, "try writeU32(&reservation, payload.")
        else
            try add(output, allocator, "try writeU32(&reservation, payload."),
        .string => try add(output, allocator, "try writeString(&reservation, payload."),
        .array => try add(output, allocator, "try writeArray(&reservation, payload."),
        .fd => unreachable,
    }
    try identifier(output, allocator, argument.name);
    switch (argument.type) {
        .int, .fixed => try add(output, allocator, "));\n"),
        .uint => try add(output, allocator, ");\n"),
        .object, .new_id => if (argument.allow_null)
            try add(output, allocator, " orelse 0);\n")
        else
            try add(output, allocator, ");\n"),
        .string, .array => try add(output, allocator, ");\n"),
        .fd => unreachable,
    }
}

fn emitDecoderCase(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    message: protocol_ir.Message,
) Error!void {
    try add(output, allocator, "            ");
    try unsigned(output, allocator, message.opcode);
    try add(output, allocator, " => decoded_message: {\n                var arguments = message.arguments();\n");
    for (message.arguments) |argument| {
        if (argument.type == .fd) continue;
        try add(output, allocator, "                const decoded_");
        try add(output, allocator, argument.name);
        try add(output, allocator, ": ");
        try emitType(output, allocator, argument);
        try add(output, allocator, " = ");
        try emitDecodeExpression(output, allocator, argument);
        try add(output, allocator, ";\n");
    }
    try add(output, allocator, "                try arguments.finish();\n");
    var fd_count: usize = 0;
    for (message.arguments) |argument| if (argument.type == .fd) {
        fd_count += 1;
    };
    if (fd_count > 0) {
        try add(output, allocator, "                if (fds.len() < ");
        try unsigned(output, allocator, fd_count);
        try add(output, allocator, ") return error.Empty;\n");
        for (message.arguments) |argument| {
            if (argument.type != .fd) continue;
            try add(output, allocator, "                const decoded_");
            try add(output, allocator, argument.name);
            try add(output, allocator, " = try fds.pop();\n");
        }
    }
    try add(output, allocator, "                break :decoded_message .{ .");
    try identifier(output, allocator, message.name);
    try add(output, allocator, " = .{");
    if (message.arguments.len > 0) try add(output, allocator, "\n");
    for (message.arguments) |argument| {
        try add(output, allocator, "                    .");
        try identifier(output, allocator, argument.name);
        try add(output, allocator, " = ");
        try add(output, allocator, "decoded_");
        try add(output, allocator, argument.name);
        try add(output, allocator, ",\n");
    }
    if (message.arguments.len > 0) try add(output, allocator, "                ");
    try add(output, allocator, "} };\n            },\n");
}

fn emitType(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    argument: protocol_ir.Argument,
) Error!void {
    if (argument.enum_name) |enum_name| {
        try emitEnumReference(output, allocator, enum_name);
        return;
    }
    const optional = argument.allow_null and switch (argument.type) {
        .string, .object, .new_id, .array => true,
        else => false,
    };
    if (optional) try add(output, allocator, "?");
    try add(output, allocator, switch (argument.type) {
        .int, .fixed => "i32",
        .uint, .object => "u32",
        .new_id => if (argument.interface == null) "DynamicNewId" else "u32",
        .string, .array => "[]const u8",
        .fd => "std.os.linux.fd_t",
    });
}

fn emitDecodeExpression(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    argument: protocol_ir.Argument,
) Error!void {
    if (argument.enum_name) |enum_name| {
        try emitEnumReference(output, allocator, enum_name);
        try add(output, allocator, ".fromInt(");
        switch (argument.type) {
            .int => try add(output, allocator, "try arguments.int()"),
            .uint => try add(output, allocator, "try arguments.uint()"),
            else => return error.InvalidEnumType,
        }
        try add(output, allocator, ")");
        return;
    }
    switch (argument.type) {
        .int, .fixed => try add(output, allocator, "try arguments.int()"),
        .uint => try add(output, allocator, "try arguments.uint()"),
        .string => if (argument.allow_null)
            try add(output, allocator, "try arguments.string()")
        else
            try add(output, allocator, "(try arguments.string()) orelse return error.UnexpectedNull"),
        .array => if (argument.allow_null)
            try add(output, allocator, "decoded_value: { const value = try arguments.array(); break :decoded_value if (value.len == 0) null else value; }")
        else
            try add(output, allocator, "try arguments.array()"),
        .object => {
            if (argument.allow_null) {
                try add(output, allocator, "decoded_value: { const id = try arguments.uint(); break :decoded_value if (id == 0) null else id; }");
            } else {
                try add(output, allocator, "decoded_value: { const id = try arguments.uint(); if (id == 0) return error.NullObject; break :decoded_value id; }");
            }
        },
        .new_id => if (argument.interface == null) {
            try add(output, allocator, "decoded_value: { const dynamic_interface = (try arguments.string()) orelse return error.UnexpectedNull; const dynamic_version = try arguments.uint(); const dynamic_id = try arguments.uint(); if (dynamic_id == 0) return error.NullObject; break :decoded_value .{ .interface = dynamic_interface, .version = dynamic_version, .id = dynamic_id }; }");
        } else if (argument.allow_null) {
            try add(output, allocator, "decoded_value: { const id = try arguments.uint(); break :decoded_value if (id == 0) null else id; }");
        } else {
            try add(output, allocator, "decoded_value: { const id = try arguments.uint(); if (id == 0) return error.NullObject; break :decoded_value id; }");
        },
        .fd => unreachable,
    }
}

fn emitEnumReference(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    reference: []const u8,
) Error!void {
    var parts = std.mem.splitScalar(u8, reference, '.');
    var first = true;
    while (parts.next()) |part| {
        if (!first) try add(output, allocator, ".");
        first = false;
        try identifier(output, allocator, part);
    }
}

fn identifier(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    name: []const u8,
) Error!void {
    try add(output, allocator, "@\"");
    try add(output, allocator, name);
    try add(output, allocator, "\"");
}

fn unsigned(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    value: anytype,
) Error!void {
    var storage: [32]u8 = undefined;
    const rendered = std.fmt.bufPrint(&storage, "{d}", .{value}) catch unreachable;
    try add(output, allocator, rendered);
}

fn add(
    output: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    bytes: []const u8,
) Error!void {
    try output.appendSlice(allocator, bytes);
}

test "generates direct typed request and event decoders" {
    const xml =
        \\<protocol name="sample"><interface name="sample_v1" version="1">
        \\<request name="set"><arg name="title" type="string"/><arg name="fd" type="fd"/></request>
        \\<event name="done"><arg name="id" type="object" allow-null="true"/></event>
        \\</interface></protocol>
    ;
    var protocol = try protocol_ir.Protocol.parse(std.testing.allocator, xml);
    defer protocol.deinit(std.testing.allocator);
    const generated = try generate(std.testing.allocator, protocol);
    defer std.testing.allocator.free(generated);
    try std.testing.expect(std.mem.indexOf(u8, generated, "pub fn decodeRequest") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "try arguments.string()") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "const decoded_fd = try fds.pop()") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "pub fn encodeRequest") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "queue.reserve(size)") != null);
}

test "expands an untyped new id into its dynamic wire arguments" {
    const xml =
        \\<protocol name="sample"><interface name="sample_v1" version="1">
        \\<request name="bind"><arg name="id" type="new_id"/></request>
        \\</interface></protocol>
    ;
    var protocol = try protocol_ir.Protocol.parse(std.testing.allocator, xml);
    defer protocol.deinit(std.testing.allocator);
    const generated = try generate(std.testing.allocator, protocol);
    defer std.testing.allocator.free(generated);
    try std.testing.expect(std.mem.indexOf(u8, generated, "id: DynamicNewId") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "Constructor_bind") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "construct_bind") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "wayring.client.NewObject") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "const dynamic_interface = (try arguments.string())") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated, "try writeString(&reservation, payload.@\"id\".interface)") != null);
}

fn generateAndDeinit(allocator: std.mem.Allocator, xml: []const u8) !void {
    var protocol = try protocol_ir.Protocol.parse(allocator, xml);
    defer protocol.deinit(allocator);
    const generated = try generate(allocator, protocol);
    allocator.free(generated);
}

test "generator releases every partial allocation" {
    const xml =
        \\<protocol name="sample"><interface name="sample" version="1">
        \\<request name="run"><arg name="value" type="uint"/></request>
        \\</interface></protocol>
    ;
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        generateAndDeinit,
        .{xml},
    );
}
